name: Pellimelam Global Radio Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install requests

    - name: Run Archive Discovery
      run: |
        python collectors/archive_discovery.py

    - name: Extract Audio
      run: |
        python processors/archive_audio_extractor.py

    - name: Clean Dataset
      run: |
        python processors/dataset_cleaner.py

    - name: Classify Instruments
      run: |
        python processors/instrument_classifier.py

    - name: Generate Radios
      run: |
        python radios/generate_radios.py

    - name: Commit updated dataset
      run: |
        git config --global user.name "pellimelam-bot"
        git config --global user.email "bot@pellimelam.com"
        git add .
        git commit -m "automatic radio dataset update" || echo "no changes"
        git push
